### ISSUE TITLE
Añadir una lista con tareas por hacer

### ISSUE THREAD

**Issue by pjuanzamora** [pjuanzamora/RiegoAutomatico-PyC#1]
Añadir una lista con tareas por hacer que se pueda hacer un "check"

**Comment by pjuanzamora** [comment]
Mira esta documentación para hacerla:
https://docs.github.com/es/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by josebullii** [comment]
Gracias :)
